// COMMEND ACTIONS
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';

// POST ACTIONS
export const ADD_POST = 'ADD_POST';
export const VIEW_POST = 'VIEW_POST';
export const DELETE_POST = 'DELETE_POST';

// TODO ACTIONS
export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
// VISIBILITY FILTER
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';